path: &data_path
  anno_file: ./data/lock3dface.json

epochs: &epochs
  max_epochs: 50

lr_cfg: &lr
  lr: 1.e-4

exp_name: &exp_name
  name: led3d_train_from_scratch

dataset:
  train_set:
    name: ImgDataset
    args: 
      <<: *data_path
      split: train
  val_set:
    name: ImgDataset
    args:
      <<: *data_path
      split: val
      test_mode: True
  batch_size: 1024
  num_workers: 16

model:
  name: ModelForCls
  args:
    model_spec:
      name: led3d
      args:
        in_channels: 1
        num_classes: 509
        drop_p: 0.9
    optimizer_spec:
      name: adamw
      args: 
        <<: *lr
        weight_decay: 0.05
    lr_sched_spec:
      name: CosineDecayWithWarmup
      args:
        warmup_fraction: 0.05
        <<: *epochs
        <<: *lr
        min_lr: 1.e-7
    num_classes: 509
    validation_on_gallery: True
    is_lock3dface: True
    <<:  *data_path

trainer:
  wandb_logger:
    <<: *exp_name
    project: Depth-Face-MAE
  checkpoint:
    every_n_epochs: 10
    dirpath: /home/mnt/rz_mnt/depth-face-mae/checkpoints
    filename: "{epoch:02d}-{global_step}"
  args:
    devices: [3]
    <<: *epochs
    log_every_n_steps: 10
    check_val_every_n_epoch: 1
    precision: 16-mixed
