path: &data_path
  anno_file: ./data/lock3dface.json

epochs: &epochs
  max_epochs: 300

lr_cfg: &lr
  lr: 6.e-4

dataset:
  train_set:
    name: ImgDataset
    args: 
      <<: *data_path
      split: train
  # val_set:
  #   name: ImgDataset
  #   args:
  #     <<: *data_path
  #     split: val
  #     test_mode: True
  batch_size: 1024
  num_workers: 16

model:
  name: ModelForMAE
  args:
    mask_ratio: 0.75
    model_spec:
      name: MAE-ViT
      args:
        img_size: 128
        patch_size: 16
        in_chans: 1
        embed_dim: 512
        depth: 12
        num_heads: 16
        mlp_ratio: 4
        decoder_embed_dim: 384
        decoder_depth: 8
        decoder_num_heads: 16
        norm_pix_loss: True
    optimizer_spec:
      name: adamw
      args: 
        <<: *lr
        weight_decay: 0.05
        betas: [0.9, 0.95]
    lr_sched_spec:
      name: CosineDecayWithWarmup
      args:
        warmup_fraction: 0.05
        <<: *epochs
        <<: *lr
        min_lr: 1.e-9

trainer:
  wandb_logger:
    name: vit_mae_v0
    project: Depth-Face-MAE
  checkpoint:
    every_n_epochs: 50
    dirpath: /home/mnt/rz_mnt/depth-face-mae/checkpoints
    filename: "{epoch:02d}-{global_step}"
  args:
    devices: [3]
    <<: *epochs
    log_every_n_steps: 10
    precision: 16-mixed
